Add option to hide author, date, comment block
Voog/design-santiago pull request #223
Opened 2020-08-04 08:24 UTC by entertthk

Known issue: blog view: js preview function not working

2020-08-11 10:53 UTC, siimha commented on components/blog-settings-editor.tpl
> +        },
Objektide lõpus üleliigsed komad

2020-08-11 10:53 UTC, siimha commented on components/blog-settings-editor.tpl
> +      show_comments = Boolean(globalDataValues.show_comments)
Muutuja lõpust semikoolon puudu

2020-08-11 10:53 UTC, siimha commented on components/blog-settings-editor.tpl
> +<div class="blog-settings-wrap">
Joondus paremale

2020-08-11 10:54 UTC, siimha commented on components/article-settings-editor.tpl
> +<div class="article-settings-wrap">
Vaata selles komonendis ka joondused, komad ja semikoolonid üle

2020-08-11 10:56 UTC, siimha commented
PRi pealkirjas võiks olla ka issue number

2020-08-12 08:12 UTC, siimha commented on layouts/blog_article.tpl
> +          <section class="post-bottom formatted cfx{% if show_article_comments == false %} hide-article-comments{% endif %}">
Siin võiks eemaldata kogu selle ala, kui kommentaare pole (hetkel on lihtsalt peidetud). See viga on mul jäänud varasemast juba sisse.
```
{% if editmode or show_article_comments == false %}
   <section class="post-bottom formatted cfx"{% if editmode and show_article_comments == false %} style="display: none;"{% endif %}>
      {% include "blog-article-comments" %}
   </section>
{% endif %}
```

Editori eelvaates saaks kasutada midagi sellist:
```
preview: function(data) {
  var $articleComment =$('.post-bottom');
  if (data.show_comments == true) {
    $articleComment.show());
  } else if (data.show_comments == false) {
    $articleComment.hide();
  }
}
```

2020-08-12 14:02 UTC, tanelj commented on components/blog-article.tpl
> +    <time class="post-date formatted cfx{% if article_data_show_date_defined != true %} site-data{% endif %}{% if show_article_date == false %} hide-article-date{% endif %}" datetime="{{ article.crea
Kui `show_article_date == false` siis ei tohi avalikus vaates ka HTML'i kuvada.

2020-08-12 14:03 UTC, tanelj commented on components/blog-settings-editor.tpl
> +      type: 'site',
Üleliigne koma.

2020-08-12 14:06 UTC, tanelj commented on layouts/blog___news.tpl
> +{% include "blog-settings-variables" %}
Kuna `{% include "blog-settings-variables" %}` includitakse `blog-article` komponendis iga artikli korral ning neid muutujaid mujal ei kasutata, siis on `blog-settings-variables` lisamine siin üleliigne.

2020-08-24 14:00 UTC, tanelj requested changes
Kena ja toimib. Vaid mõned koodi stiililised issued ja veidi üleliigset koodi tuleks veel korrigeerida.

2020-08-26 10:57 UTC, tanelj requested changes
Muidu töötab, kuid ühe `undefinded` ehk defineerimata väärtuse veal leidsin. Mitmes kohas peaks `!== null` asemel olema `!= null`.

2020-08-26 10:57 UTC, tanelj commented on components/article-settings-editor.tpl
> +    if (articleDataValues.show_comments !== null && articleDataValues.show_comments !== '') {
Kui artiklil data's ei ole `show_comments` defineeritud, siis on `articleDataValues.show_comments` väärtusekd `undefined`.

Praegusel hetkel kuvab artikli vaade seaded sel juhul alati väärtuseid välja lülitatuna, kuna `Boolean(undefinded) => fasle`.

Seega peab siin ja all pool kontrollima ka nulli laadse objekti olemasolu ehk range võrdluse asemel `!==` hoopis `!=`.

Seega siin:

`articleDataValues.show_comments != null`

2020-08-26 10:57 UTC, tanelj commented on components/article-settings-editor.tpl
> +    } else if (globalDataValues.show_comments !== null && globalDataValues.show_comments !== '') {
Ka siin peab olema `!== null` asemel `!= null`.

2020-08-26 10:57 UTC, tanelj commented on components/article-settings-editor.tpl
> +    if (articleDataValues.show_date !== null && articleDataValues.show_date !== '') {
Ka siin peab olema `!== null` asemel `!= null`.

2020-08-26 10:57 UTC, tanelj commented on components/article-settings-editor.tpl
> +    } else if (globalDataValues.show_dates !== null && globalDataValues.show_dates !== '') {
Ka siin peab olema `!== null` asemel `!= null`.

2020-08-26 10:57 UTC, tanelj commented on components/blog-settings-editor.tpl
> +    if (globalDataValues.show_comments !== null && globalDataValues.show_comments !== '') {
Ka siin peab olema `!== null` asemel `!= null`.

2020-08-26 10:57 UTC, tanelj commented on components/blog-settings-editor.tpl
> +    if (globalDataValues.show_dates !== null && globalDataValues.show_dates !== '') {
Ka siin peab olema `!== null` asemel `!= null`.

2020-08-27 20:46 UTC, tanelj approved these changes

2020-08-31 14:01 UTC, siimha approved these changes
Super töö!

2020-08-31 19:11 UTC, merged