Make auto-rendered product page image clickable
Voog/design-santiago pull request #232
Opened 2022-02-09 14:12 UTC by PeeterPaal

Closes #231

2022-02-09 14:40 UTC, tanelj requested changes
Works as expected., but some naming comments.

2022-02-09 14:40 UTC, tanelj commented on sources/javascripts/concat/base.js
> +  var handleProductImageClick = function(url) {
Let's rename as it actually is: `id` or slug not `url`.

```suggestion
  var handleProductImageClick = function(product_id) {
```

2022-02-09 14:40 UTC, tanelj commented on sources/javascripts/concat/base.js
> +      $('.product-content .item-top').click(function() {
`item-top` is quit random target. Let's add `product-image` class to product image div.

2022-02-09 14:40 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +        template.handleProductImageClick("{{ product.id }}");
Let's add this line only in edit mode. No need to present in live html body. Also no need to add quotes arround id (that is number).
```suggestion

        {%- if product and editmode %}
          template.handleProductImageClick({{ product.id }});
        {%- endif %}
```

2022-02-09 14:57 UTC, tanelj approved these changes
Nice!

2022-02-10 13:08 UTC, pxska approved these changes

2022-02-10 20:12 UTC, merged