Add various design improvements
Voog/design-santiago pull request #239
Opened 2022-05-17 12:30 UTC by PeeterPaal

- Use `object.og_image` method for OG image
- Add titles & tooltips to various content areas

Closes #237 
Closes #238

2022-05-18 14:14 UTC, tanelj requested changes
Nice, but some improvements:
* "Blog article" `additional_body` use additional_content and content_tooltip_additional_information

2022-05-18 14:14 UTC, tanelj commented on components/layout-footer.tpl
> +      <div class="content-area">{% xcontent name="footer_2" title=footer_content_title title_tooltip=footer_content_title_tooltip %}</div>
Its too narrow text area. Let's keep only `title_tooltip`
```suggestion
      <div class="content-area">{% xcontent name="footer_2" title_tooltip=footer_content_title_tooltip %}</div>
```

2022-05-23 08:47 UTC, tanelj approved these changes
Nice!

2022-05-23 11:43 UTC, pxska approved these changes
A small comment + check for long lines. Otherwise good!

2022-05-23 11:43 UTC, pxska commented on components/blog-article.tpl
>      {% endif %}
Indentation is wrong here:
```suggestion
      <div>
        <time class="post-date formatted cfx{% if article_data_show_date_defined != true %} site-data{% endif %}{% if show_article_date == false %} hide-article-date{% endif %}" datetime="{{ article.created_at | date: '%Y-%m-%d' }}">{{ article.created_at | format_date: article_date_format }}</time>
      </div>
    {% endif %}
```

2022-05-24 07:33 UTC, robertpih approved these changes

2022-05-24 12:02 UTC, merged